import React from 'react'

export default function GabbyFoodCalculator() {
    // create the array of objects for the data
    var objectCarbs = [
        {
            item: 'Rice(Cooked)',
            weight: 100,
            carbs: 28,
            fat: 0.3,
            protein: 2.7,
            calories: 130,
        },
        {
            item: 'White Potato',
            weight: 100,
            carbs: 22.3,
            fat: 0.1,
            protein: 2.1,
            calories: 87,
        },
        {
            item: 'Sweet Potato',
            weight: 100,
            carbs: 20,
            fat: 0.1,
            protein: 1.6,
            calories: 86,
        },
        {
            item: 'Criolla Potato',
            weight: 100,
            carbs: 19,
            fat: 0,
            protein: 3,
            calories: 90,
          },
        {
            item: 'Yuca',
            weight: 100,
            carbs: 26.8,
            fat: 0.4,
            protein: 3.1,
            calories: 120,
        },
        {
            item: 'Plantain',
            weight: 100,
            carbs: 32,
            fat: 0.4,
            protein: 1.3,
            calories: 122,
          },
          {
            item: 'Quinoa',
            weight: 100,
            carbs: 21.1,
            fat: 2.2,
            protein: 4.3,
            calories: 120,
          },
          {
            item: 'Lentils',
            weight: 100,
            carbs: 12.2,
            fat: 0.4,
            protein: 9,
            calories: 88,
          },
          {
            item: 'Black Beans (Cooked)',
            weight: 100,
            carbs: 15,
            fat: 0.5,
            protein: 8.9,
            calories: 100,
          },
          {
            item: 'Chickpeas (Cooked)',
            weight: 100,
            carbs: 27.4,
            fat: 2.6,
            protein: 8.9,
            calories: 100,
          },
          {
            item: 'Strawberries',
            weight: 100,
            carbs: 7.7,
            fat: 0.3,
            protein: 0.7,
            calories: 32,
          },
          {
            item: 'Bluberries',
            weight: 100,
            carbs: 14.5,
            fat: 0.3,
            protein: 0.7,
            calories: 57,
          },
          {
            item: 'Blackberries',
            weight: 100,
            carbs: 9.6,
            fat: 0.5,
            protein: 1.4,
            calories: 43,
          },
          {
            item: 'Raspberries',
            weight: 100,
            carbs: 11.9,
            fat: 0.6,
            protein: 1.2,
            calories: 52,
          },
          {
            item: 'Banana',
            weight: 100,
            carbs: 22.8,
            fat: 0.3,
            protein: 1.1,
            calories: 89,
          },
          {
            item: 'Papaya',
            weight: 100,
            carbs: 9.8,
            fat: 0,
            protein: 0.1,
            calories: 39,
          },
          {
            item: 'Watermelon',
            weight: 100,
            carbs: 7.6,
            fat: 0.2,
            protein: 0.6,
            calories: 30,
          },
          {
            item: 'Kiwi',
            weight: 100,
            carbs: 15,
            fat: 0.5,
            protein: 1.1,
            calories: 61,
          },
          {
            item: 'Mango',
            weight: 100,
            carbs: 15,
            fat: 0.4,
            protein: 0.8,
            calories: 60,
          },
          {
            item: 'Pineapple',
            weight: 100,
            carbs: 13.1,
            fat: 0.1,
            protein: 0.5,
            calories: 50,
          },
          {
            item: 'Tangerine',
            weight: 100,
            carbs: 13.3,
            fat: 0.3,
            protein: 0.8,
            calories: 53,
          },
          {
            item: 'Orange',
            weight: 100,
            carbs: 11.8,
            fat: 0.1,
            protein: 0.9,
            calories: 47,
          },
          {
            item: 'Honeydew',
            weight: 100,
            carbs: 9,
            fat: 0.1,
            protein: 0.5,
            calories: 36,
          },
          {
            item: 'Grapes',
            weight: 100,
            carbs: 17.1,
            fat: 0.3,
            protein: 0.6,
            calories: 67,
          },
          {
            item: 'Pear',
            weight: 100,
            carbs: 15.2,
            fat: 0.1,
            protein: 0.4,
            calories: 57,
          },
          {
            item: 'Red Apple',
            weight: 100,
            carbs: 14.1,
            fat: 0.2,
            protein: 0.3,
            calories: 59,
          },
          {
            item: 'Green Apple',
            weight: 100,
            carbs: 13.6,
            fat: 0.2,
            protein: 0.4,
            calories: 58,
          },
          {
            item: 'Peach',
            weight: 100,
            carbs: 10.1,
            fat: 0.3,
            protein: 0.9,
            calories: 42,
          },
          {
            item: 'Pomegranate',
            weight: 100,
            carbs: 18.7,
            fat: 1.2,
            protein: 1.7,
            calories: 83,
          },
          {
            item: 'Figs',
            weight: 100,
            carbs: 19.2,
            fat: 0.3,
            protein: 0.8,
            calories: 74,
          },
          {
            item: 'Carrot',
            weight: 100,
            carbs: 9.6,
            fat: 0.2,
            protein: 0.9,
            calories: 41,
          },
          {
            item: 'Pumpkin',
            weight: 100,
            carbs: 6.5,
            fat: 0.1,
            protein: 1,
            calories: 26,
          },
          {
            item: 'Zucchini',
            weight: 100,
            carbs: 3.1,
            fat: 0.3,
            protein: 1.2,
            calories: 17,
          },
          {
            item: 'Corn',
            weight: 100,
            carbs: 18.7,
            fat: 1.4,
            protein: 3.3,
            calories: 86,
          },
          {
            item: 'Tomato',
            weight: 100,
            carbs: 3.9,
            fat: 0.2,
            protein: 0.9,
            calories: 18,
          },
          {
            item: 'Spinach',
            weight: 100,
            carbs: 3.6,
            fat: 0.4,
            protein: 0.9,
            calories: 18,
          },
          {
            item: 'Kale',
            weight: 100,
            carbs: 4.4,
            fat: 1.5,
            protein: 2.9,
            calories: 35,
          },
          {
            item: 'Arugula',
            weight: 100,
            carbs: 3.7,
            fat: 0.7,
            protein: 2.6,
            calories: 25,
          },
          {
            item: 'Cucumber',
            weight: 100,
            carbs: 3.6,
            fat: 0.1,
            protein: 0.6,
            calories: 15,
          },
          {
            item: 'Celery',
            weight: 100,
            carbs: 3,
            fat: 0.2,
            protein: 0.7,
            calories: 16,
          },
          {
            item: 'Broccoli',
            weight: 100,
            carbs: 6.6,
            fat: 0.4,
            protein: 2.8,
            calories: 34,
          },
          {
            item: 'Cauliflower',
            weight: 100,
            carbs: 5,
            fat: 0.3,
            protein: 1.9,
            calories: 25,
          },
          {
            item: 'Asparagus',
            weight: 100,
            carbs: 3.9,
            fat: 0.1,
            protein: 2.2,
            calories: 20,
          },
          {
            item: 'Bell Pepper',
            weight: 100,
            carbs: 6,
            fat: 0.3,
            protein: 1,
            calories: 26,
          },
          {
            item: 'Red Cabbage',
            weight: 100,
            carbs: 7.4,
            fat: 0.2,
            protein: 1.4,
            calories: 31,
          },
          {
            item: 'Eggplant',
            weight: 100,
            carbs: 5.9,
            fat: 0.2,
            protein: 1,
            calories: 25,
          },
          {
            item: 'Whit Mushroom',
            weight: 100,
            carbs: 3.3,
            fat: 0,
            protein: 3.1,
            calories: 22,
          },
          {
            item: 'Brussel Sprout',
            weight: 100,
            carbs: 8.9,
            fat: 0.3,
            protein: 3.4,
            calories: 43,
          },
          {
            item: 'White Onion',
            weight: 100,
            carbs: 3.3,
            fat: 0.1,
            protein: 1.1,
            calories: 40,
          },
          {
            item: 'Ezekiel Flourless Sprouted Grain Bread (1 Slice)',
            weight: 100,
            carbs: 15,
            fat: 0.5,
            protein: 5,
            calories: 80,
          },
          {
            item: 'Pan Trenzado de Arroz Siempre Natural',
            weight: 100,
            carbs: 25.5,
            fat: 7.3,
            protein: 3.6,
            calories: 185,
          },
    ]


    var objectFats = [
        {
            item: 'Avocado',
            weight: 100,
            carbs: 8.5,
            fat: 14.7,
            protein: 2,
            calories: 160,
        },
    ]
    return (
        <div>GabbyFoodCalculator</div>
    )
}
